version: '3'
services:
  frontend:
    build: ./frontend19v
    ports:
      - "9998:9998"
    depends_on:
      - backend
  backend:
    build: ./BackEnd19v
    ports:
      - "8080:8080"
    depends_on:
      - fuseki
      - mongo
  fuseki:
    image: stain/jena-fuseki
    environment:
      - ADMIN_PASSWORD=D0rlghQl5IAgYOm
    ports:
      - "3030:3030"
  mongo:
    build: ./mongo
    ports:
      - "27020:27017"
  causeapi:
    image: tjuyinkanglin/causality_analysis
    ports:
      - "10080:10080"