version: '3'
services:
  frontend:
    build: ./frontend19v
    ports:
      - "9998:9998"
    depends_on:
      - backend
  backend:
    build: ./BackEnd19v
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    build: ./mongo
    ports:
      - "27020:27017"